# 원어민 보고서 업무 자동화 코드

### 1. 패키지 설치

In [ ]:
pip install docx-mailmerge==0.5.0

### 2. 모듈 임포트

In [7]:
import os
import shutil
import pandas as pd
from mailmerge import MailMerge

In [8]:
folderName = "Evaluation Report 4 Weeks - Gangwon Camp"
template = "gangwon_4weeks_template.docx"
nameList = "gangwon_4weeks_namelist.csv"

### 3. 워드 템플릿 로드

In [9]:
document = MailMerge(template)
print(document.get_merge_fields())

{'sTeacher', 'className', 'ps', 'rTeacher', 'wTeacher', 'speaking', 'pw', 'fs', 'Gender', 'ft', 'ms', 'mt', 'kName', 'pt', 'eName', 'fw', 'Grade', 'mw'}

### 4. 레벨 테스트 점수 엑셀 데이터 로드

In [10]:
scoreTable = pd.read_csv(nameList)
scoreTable = scoreTable.astype("O")
scoreTable

,kName,eName,Grade,Gender,className,sTeacher,rTeacher,wTeacher,ps,pw,pt,ms,mw,mt
0,박시우,Shiwoo,2,Male,Bohemian,David,Jorge,Kevin,10,20,30,29.0,26.0,55.0
1,박태성,Taeseong,3,Male,Bohemian,David,Jorge,Kevin,14,24,38,36.5,42.0,78.5
2,이서진,Jake,3,Male,Bohemian,David,Jorge,Kevin,18,14,32,37.0,21.0,58.0
3,오하린,Julia,4,Female,Bohemian,David,Jorge,Kevin,34,28,62,38.5,42.0,80.5
4,이지환,David,4,Male,Bohemian,David,Jorge,Kevin,10,18,28,36.5,37.0,73.5
5,서지후,Jihu,4,Male,Bohemian,David,Jorge,Kevin,10,26,36,34.5,35.0,69.5
6,한혜인,Teresa,4,Female,Bohemian,David,Jorge,Kevin,16,24,40,35.5,43.0,78.5
7,이하람,Aiden,5,Male,Bohemian,David,Jorge,Kevin,10,22,32,32.0,32.0,64.0
8,이하진,Riley,5,Female,Bohemian,David,Jorge,Kevin,26,28,54,32.0,39.0,71.0
9,공지윤,Jiyun,5,Female,Bohemian,David,Jorge,Kevin,26,25,51,36.5,58.0,94.5
10,박선호,Ryan,5,Male,Bohemian,David,Jorge,Kevin,32,30,62,27.0,39.0,66.0
11,이민준,Jun,4,Male,Pinetree,David,Jorge,Kevin,34,42,76,40.0,49.0,89.0
12,김경민,KyeongMin,4,Male,Pinetree,David,Jorge,Kevin,32,28,60,39.5,55.0,94.5
13,황리하,Bella,4,Female,Pinetree,David,Jorge,Kevin,30,49,79,36.5,53.0,89.5
14,임채후,Jake,5,Male,Pinetree,David,Jorge,Kevin,26,38,64,34.0,56.0,90.0
15,이선현,Helen,5,Female,Pinetree,David,Jorge,Kevin,14,26,40,40.0,58.0,98.0
16,임지은,Lora,5,Female,Pinetree,David,Jorge,Kevin,17,38,55,30.0,53.0,83.0
17,문정연,Julian,5,Female,Pinetree,David,Jorge,Kevin,18,40,58,37.0,51.0,88.0
18,김민준,MJ,6,Male,Pinetree,David,Jorge,Kevin,14,48,62,22.0,52.0,74.0
19,박치우,Chiwoo,6,Male,Pinetree,David,Jorge,Kevin,13,30,43,22.0,32.5,54.5
20,이채원,Luna,4,Female,Bouquet,David,Jorge,Kevin,30,40,70,34.0,55.0,89.0
21,이영현,Alice,5,Female,Bouquet,David,Jorge,Kevin,24,52,76,33.0,54.0,87.0
22,민송윤,Sam,5,Male,Bouquet,David,Jorge,Kevin,26,52,78,25.0,56.0,81.0
23,함예든,Jenny,5,Female,Bouquet,David,Jorge,Kevin,30,45,75,32.0,60.0,92.0
24,임태희,Clara,5,Female,Bouquet,David,Jorge,Kevin,34,56,90,33.0,59.0,92.0
25,박하언,Paul,6,Male,Bouquet,David,Jorge,Kevin,16,48,64,23.0,58.5,81.5
26,전윤희,Leila,6,Female,Bouquet,David,Jorge,Kevin,30,34,64,31.0,51.0,82.0
27,이화연,Luna,6,Female,Bouquet,David,Jorge,Kevin,30,45,75,28.0,53.0,81.0
28,문유빈,Sophia,5,Female,Forever,David,Jorge,Kevin,30,43,73,36.0,53.5,89.5
29,신비아,Bia,6,Female,Forever,David,Jorge,Kevin,34,40,74,34.0,50.0,84.0
30,최선재,Jenny,6,Female,Forever,David,Jorge,Kevin,33,52,85,35.0,56.0,91.0
31,이주찬,Juchan,7,Male,Forever,David,Jorge,Kevin,32,45,77,34.0,49.5,83.5
32,조현우,Jayden,7,Male,Forever,David,Jorge,Kevin,29,44,73,34.0,53.0,87.0
33,강지민,Jimin,7,Female,Forever,David,Jorge,Kevin,32,48,80,34.0,54.0,88.0
34,도원재,Jason,7,Male,Forever,David,Jorge,Kevin,31,47,78,34.0,55.0,89.0
35,홍진표,Jason,7,Male,Forever,David,Jorge,Kevin,31,48,79,34.0,54.0,88.0
36,권규리,Jenny,7,Female,Forever,David,Jorge,Kevin,35,58,93,37.0,60.0,97.0

### 5. 반 별 폴더 생성

In [11]:
os.makedirs(folderName)
for i, n in enumerate(scoreTable.className.unique()):
    os.makedirs(f"{folderName}/{n}")

### 6. 데이터에 맞게 워드파일 생성 후 반 별 폴더로 이동

In [12]:
for i in range(len(scoreTable)):
    document = MailMerge(template)
    document.merge(
        kName = str(scoreTable.iloc[i][0]),
        eName = str(scoreTable.iloc[i][1]),
        Grade = str(scoreTable.iloc[i][2]),
        Gender = str(scoreTable.iloc[i][3]),
        className = str(scoreTable.iloc[i][4]),
        sTeacher = str(scoreTable.iloc[i][5]),
        rTeacher = str(scoreTable.iloc[i][6]),
        wTeacher = str(scoreTable.iloc[i][7]),
        ps = str(scoreTable.iloc[i][8]),
        pw = str(scoreTable.iloc[i][9]),
        pt = str(scoreTable.iloc[i][10]),
        ms = str(scoreTable.iloc[i][11]),
        mw = str(scoreTable.iloc[i][12]),
        mt = str(scoreTable.iloc[i][13])
    )
    file_name = f"{scoreTable.iloc[i][1]}({scoreTable.iloc[i][0]})-{scoreTable.iloc[i][4]}.docx"
    path_name = f"{folderName}/{scoreTable.iloc[i][4]}"
    document.write(file_name)
    shutil.move(file_name, path_name)